In [2]:
import numpy as np

In [3]:
a = np.array([1, 3, 4])
b = np.array([1, 4, 6])
np.dot(a, b)

37

In [4]:
a * b

array([ 1, 12, 24])

In [5]:
np.exp(a)

array([ 2.71828183, 20.08553692, 54.59815003])

In [9]:
np.zeros(3).shape

(3,)

In [10]:
np.zeros((3,)).shape

(3,)

In [14]:
a = np.array([[1,3,4], [1, 4, 5], [5, 4, 5]])
w = np.array([2, 3, 4])
np.dot(w.T, a)

array([25, 34, 43])

In [6]:
A = np.array([[56., 0., 4.4, 67.], 
              [1.2, 105., 54., 5.],
              [1.5, 135., 99., 4.5]])

In [8]:
A.sum(1).reshape(-1, 1)

array([[127.4],
       [165.2],
       [240. ]])

In [9]:
A / A.sum(1).reshape(-1, 1)

array([[0.43956044, 0.        , 0.03453689, 0.52590267],
       [0.00726392, 0.63559322, 0.32687651, 0.03026634],
       [0.00625   , 0.5625    , 0.4125    , 0.01875   ]])

In [18]:
A.sum(0).shape

(4,)

In [19]:
A.sum(0).reshape((1, 4))

array([[ 58.7, 240. , 157.4,  76.5]])

In [20]:
A / A.sum(0).reshape((1, 4))

array([[0.95400341, 0.        , 0.02795426, 0.87581699],
       [0.02044293, 0.4375    , 0.34307497, 0.06535948],
       [0.02555366, 0.5625    , 0.62897078, 0.05882353]])

In [21]:
a = np.random.randn(5, 1)

In [23]:
a

array([[0.14386806],
       [0.48352493],
       [1.39687735],
       [0.66569292],
       [0.39434506]])

In [24]:
a.T

array([[0.14386806, 0.48352493, 1.39687735, 0.66569292, 0.39434506]])

In [25]:
np.dot(a, a.T)

array([[0.02069802, 0.0695638 , 0.20096604, 0.09577195, 0.05673366],
       [0.0695638 , 0.23379636, 0.67542503, 0.32187913, 0.19067567],
       [0.20096604, 0.67542503, 1.95126633, 0.92989137, 0.55085168],
       [0.09577195, 0.32187913, 0.92989137, 0.44314707, 0.26251271],
       [0.05673366, 0.19067567, 0.55085168, 0.26251271, 0.15550802]])